{
# 【1. 公众号配置：所有信息都在刚注册的公众号中找到】
# 公众号appId，替换掉下方文字内容，不要删除双引号
"app_id": "wx5928f551512982fe",

# 公众号appSecret，替换掉下方文字内容，不要删除双引号
"app_secret": "320c96093b8d3e82d4f1a5dd6f01e306",

# 模板消息接口里的模板ID，替换掉下方文字内容，不要删除双引号
"template_id": "PYxxJ8ZqtCxZfgpxOFJU1229DcvuQEQt6ZoBhqUCH3o	",

# 接收公众号消息的微信号（user-id），如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["o2TTS6uvseBEdvcHxuNAm_v3-1WA","***2"],

# 【2. 信息配置】
# 所在省份
"province": "江西",

# 所在城市
"city": "景德镇",

# 生日1，如果生日为农历，在最前面加上r即可，如r1999-01-01
"birthday1": "2002-10-23",
# 生日2
"birthday2": "2003-05-05",

# 在一起的日子，格式同上
"love_date": "2024-01-01",


#######################################
#########【3.是否启用每日一句英语】##########
#######################################
#如果要启用，请把下面的 否 改为 是 ，注意要保留双引号
#如果不用这个接口，请不要改动里面的内容
"Whether_Eng":"否",
###注意要在消息模板中加入{{note_ch.DATA}}和{{note_en.DATA}}，才能够正常显示


#######################################
#############【4.彩虹屁API设置】#############
#######################################
#请把你申请的彩虹屁API接口替换掉下方的文字"替换掉我"，注意要保留双引号
#如果不用这个接口，请不要改动里面的内容

"caihongpi_API":"79953ceef2eff83e8cf9a66870b21757",

###注意要在消息模板中加入{{pipi.DATA}}，才能够正常显示

#######################################
#############【5.励志古言API设置】###########
#######################################
#请把你申请的励志古言API接口替换掉下方的文字"替换掉我"，注意要保留双引号
#如果不用这个接口，请不要改动里面的内容

#替换成key 
"lizhi_API":"79953ceef2eff83e8cf9a66870b21757",

###注意要在消息模板中加入{{lizhi.DATA}}，才能够正常显示

#######################################
#############【6.天气预报API设置】###########
#######################################
#请把你申请的天气预报API接口替换掉下方的文字"替换掉我"，注意要保留双引号
#如果不用这个接口，请不要改动里面的内容
#这个API本程序目前只提取了当天的天气情况，只会给出当天降雨量以及出行建议。
#如果需要提取未来日期需要等待开发，或者自行更改源码。

"tianqi_API":"79953ceef2eff83e8cf9a66870b21757",

###注意要在消息模板中加入{{tianqi.DATA}}，才能够正常显示


#######################################
###########【7.健康小提示API设置】###########
#######################################
#请把你申请的健康小提示API接口替换掉下方的文字"替换掉我"，注意要保留双引号
#如果不用这个接口，请不要改动里面的内容

"health_API":"79953ceef2eff83e8cf9a66870b21757",

###注意要在消息模板中加入{{health.DATA}}，才能够正常显示

#######################################
#############【8.星座运势API设置】###########
#######################################
#请把你申请的星座运势API接口替换掉下方的文字"替换掉我"，注意要保留双引号
#如果不用这个接口，请不要改动里面的内容

"lucky_API":"替换掉我",
#请在下方填入你的星座，中文即可，如"天蝎座"
"astro":"射手座"
###注意要在消息模板中加入{{lucky.DATA}}，才能够正常显示
}

